# map을 이용한 input().split() int 형변환 map(자료형, input().split())
A,B = map(int, input().split())
print("{}".format(A+B))
print("{}".format(A-B))
print("{}".format(A*B))
print("{}".format(int(A/B)))
print("{}".format(A%B))